Repository: plone.app.dexterity


Branch: refs/heads/master
Date: 2018-10-06T17:00:28+02:00
Author: Maurits van Rees (mauritsvanrees) <maurits@vanrees.org>
Commit: https://github.com/plone/plone.app.dexterity/commit/335981d373247751c6ab14367c7d4d8a1a34a5a6

Release upload lock when name chooser fails.

Fixes https://github.com/plone/plone.app.dexterity/issues/276

Files changed:
A news/276.bugfix
M plone/app/dexterity/factories.py

b"diff --git a/news/276.bugfix b/news/276.bugfix\nnew file mode 100644\nindex 0000000..a941f88\n--- /dev/null\n+++ b/news/276.bugfix\n@@ -0,0 +1 @@\n+Release upload lock when name chooser fails.  [maurits]\ndiff --git a/plone/app/dexterity/factories.py b/plone/app/dexterity/factories.py\nindex 2734819..ce89521 100644\n--- a/plone/app/dexterity/factories.py\n+++ b/plone/app/dexterity/factories.py\n@@ -35,9 +35,8 @@ def __call__(self, name, content_type, data):\n         # otherwise I get ZPublisher.Conflict ConflictErrors\n         # when uploading multiple files\n         upload_lock.acquire()\n-\n-        newid = chooser.chooseName(name, self.context.aq_parent)\n         try:\n+            newid = chooser.chooseName(name, self.context.aq_parent)\n             # Try to determine which kind of NamedBlob we need\n             # This will suffice for standard p.a.contenttypes File/Image\n             # and any other custom type that would have 'File' or 'Image' in\n"

