Repository: plone.resourceeditor


Branch: refs/heads/master
Date: 2018-10-02T11:43:48+02:00
Author: Thomas Massmann (tmassman) <thomas.massmann@it-spir.it>
Commit: https://github.com/plone/plone.resourceeditor/commit/a4092dc4f04b05725196d23aba840cd03eee5e53

Fix UnicodeDecodeError when saving files TTW.

Encode is done earlier now for Py2 which caused double encoding.

Files changed:
M CHANGES.rst
M plone/resourceeditor/browser.py

b"diff --git a/CHANGES.rst b/CHANGES.rst\nindex 8e1409e..16cc40e 100644\n--- a/CHANGES.rst\n+++ b/CHANGES.rst\n@@ -14,7 +14,8 @@ New features:\n \n Bug fixes:\n \n-- *add item here*\n+- Fix UnicodeDecodeError when saving files TTW.\n+  [tmassman]\n \n \n 2.1.2 (2018-09-28)\ndiff --git a/plone/resourceeditor/browser.py b/plone/resourceeditor/browser.py\nindex ad18380..b930e48 100644\n--- a/plone/resourceeditor/browser.py\n+++ b/plone/resourceeditor/browser.py\n@@ -256,7 +256,7 @@ def saveFile(self, path, value):\n             # (useful when we compile less from the theming editor)\n             return json.dumps({'success': 'tmp', 'value': value})\n         else:\n-            self.context.writeFile(path, value.encode('utf-8'))\n+            self.context.writeFile(path, value)\n             return json.dumps({'success': 'save'})\n \n     def addFolder(self, path, name):\n"

